[package]
name = "cypher-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cypher-common.workspace = true
bytes.workspace = true
thiserror.workspace = true
crc32fast.workspace = true

[build-dependencies]
nom.workspace = true
crc32fast.workspace = true

[lints]
workspace = true
