[package]
name = "cypher-tls"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
cypher-types.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
rcgen.workspace = true
webpki-roots.workspace = true
rustls-native-certs = "0.8"
tokio.workspace = true
tracing.workspace = true


[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
