[package]
name = "cypher-transfer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cypher-common.workspace = true
cypher-proto.workspace = true
cypher-crypto.workspace = true
cypher-transport.workspace = true
tokio.workspace = true
bytes.workspace = true
thiserror.workspace = true
tracing.workspace = true
sha2.workspace = true
futures.workspace = true
zstd.workspace = true

[lints]
workspace = true
