[package]
name = "signaling"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cypher-types.workspace = true
cypher-wire.workspace = true
cypher-crypto.workspace = true
cypher-server-kit.workspace = true
tokio.workspace = true
tokio-util.workspace = true
bytes.workspace = true
tracing.workspace = true
anyhow.workspace = true
redis.workspace = true
async-nats.workspace = true
rand.workspace = true
futures.workspace = true
serde.workspace = true
prometheus.workspace = true
hex.workspace = true
x25519-dalek.workspace = true

[lints]
workspace = true
