[package]
name = "cypher-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cypher-common.workspace = true
x25519-dalek.workspace = true
ed25519-dalek.workspace = true
aes-gcm.workspace = true
hkdf.workspace = true
sha2.workspace = true
rand.workspace = true
thiserror.workspace = true
bytes.workspace = true
serde.workspace = true
zeroize.workspace = true
argon2.workspace = true
bip39.workspace = true
postcard.workspace = true

[lints]
workspace = true
