[package]
name = "gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cypher-types.workspace = true
cypher-wire.workspace = true
cypher-tls.workspace = true
cypher-transport = { workspace = true, features = ["ws"] }
cypher-server-kit.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tokio-rustls.workspace = true
bytes.workspace = true
dashmap.workspace = true
tracing.workspace = true
anyhow.workspace = true
async-nats.workspace = true
futures.workspace = true
serde.workspace = true
prometheus.workspace = true
rand.workspace = true
ed25519-dalek.workspace = true

[dev-dependencies]
tokio-stream.workspace = true
cypher-core.workspace = true
cypher-crypto.workspace = true
rand_chacha.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
