[package]
name = "load-test"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
cypher-types.workspace = true
cypher-wire.workspace = true
cypher-crypto.workspace = true
cypher-tls.workspace = true
cypher-transport.workspace = true
tokio.workspace = true
bytes.workspace = true
futures.workspace = true
rustls.workspace = true
tracing.workspace = true
anyhow.workspace = true
clap.workspace = true

[lints]
workspace = true
