[package]
name = "load-test"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cypher-common.workspace = true
cypher-crypto.workspace = true
cypher-proto.workspace = true
cypher-tls.workspace = true
cypher-transport.workspace = true
tokio.workspace = true
bytes.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }

[lints]
workspace = true
