global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:9090"]

  - job_name: "signaling"
    static_configs:
      - targets: ["signaling:9091"]

  - job_name: "relay"
    static_configs:
      - targets: ["relay:9092"]
