[package]
name = "cypher-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
ws = ["dep:tokio-tungstenite"]

[dependencies]
cypher-types.workspace = true
bytes.workspace = true
futures.workspace = true
tracing.workspace = true
tokio-tungstenite = { workspace = true, optional = true }
tokio.workspace = true
tokio-util.workspace = true
tokio-rustls.workspace = true
rustls.workspace = true

[dev-dependencies]
cypher-tls.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
