[package]
name = "cypher-wire"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bytes.workspace = true
thiserror.workspace = true
sha2.workspace = true
cypher-types.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true

[[bench]]
name = "wire"
harness = false

[lints]
workspace = true
